version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb:/data/db
    container_name: "mongodb_compose"
    ports:
    - 27017:27017
  app:
    image: philosup/demo:latest
    ports:
    - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    